In [1]:
 import numpy as np
    

In [3]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [6]:
b = np.array([[[1,2,3,4,5]],[[1,2,3,4,5]],[[1,2,3,4,5]]])
print (b)

[[[1 2 3 4 5]]

 [[1 2 3 4 5]]

 [[1 2 3 4 5]]]


In [7]:
b[0,0,-1]

5

In [10]:
c = np.array([[[1,2],[1,2]],[[3,4],[3,4]],[[5,6],[5,6]]])
print(c)

[[[1 2]
  [1 2]]

 [[3 4]
  [3 4]]

 [[5 6]
  [5 6]]]


In [13]:
c[2][1][0]

5

In [15]:
c[:,0,:] = [3,4]
print (c)

[[[3 4]
  [1 2]]

 [[3 4]
  [3 4]]

 [[3 4]
  [5 6]]]


In [17]:
np.zeros((5,5,2))


array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
np.full((4,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [20]:
np.random.rand(4,2)

array([[0.20572518, 0.70567906],
       [0.73407807, 0.36536444],
       [0.80054519, 0.8416101 ],
       [0.0403155 , 0.19648925]])

In [166]:
np.random.randint(-5,6, size=(5,5))

array([[ 5,  4, -4,  5,  4],
       [-3, -4, -1, -2, -3],
       [-4,  5, -2,  1,  3],
       [-5, -3, -4, -5,  0],
       [ 4,  1, -5,  4, -4]])

In [171]:
a = np.full((5,5),1)
print(a)
z = np.zeros((3,3))
z[1,1] = 9

a[1:4,1:4] = z

print (a)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [173]:
a = np.zeros((2,2))
b = a.copy()
b[0,0]= 5
print(a)
print(b)

[[0. 0.]
 [0. 0.]]
[[5. 0.]
 [0. 0.]]


In [178]:
a = np.array((1,2,3,4,5))
print (a)

a +2
print (a+2)
a -2+2
print (a)
a *2
print (a)
a /2
print (a)

[1 2 3 4 5]
[3 4 5 6 7]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
algebra

In [182]:
a = np.ones((2,3))
print(a)
b= np.full((3,2),2)
print(b)

np.matmul(a,b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [183]:
a = np.array((1,2,3,4,5,6,7,8,9,0))
a[a>4]

array([5, 6, 7, 8, 9])

In [195]:
a = np.array([(1,2,3,4,5),(6,7,8,9,10),(11,12,13,14,15),(16,17,18,19,20),(21,22,23,24,25),(26,27,28,29,30)])
a[2:4,0:2]
a[[0,1,2,3],[1,2,3,4]]
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])