# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
a = np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [10]:
a = np.arange(10,50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [48]:
a = np.arange(9).reshape(3,3)

print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [17]:
a = np.array([1,2,0,0,4,0])
print(a[a>0])

[1 2 4]


#### 8. Create a 3x3x3 array with random values (★☆☆)

In [19]:
a = np.random.randint(-5,5,size=(3,3,3))
print(a)

[[[-5  3  4]
  [-3 -5  2]
  [-2 -1  2]]

 [[ 0 -2  1]
  [ 1 -2 -1]
  [-1  3  3]]

 [[-1  4  1]
  [ 3  4  1]
  [ 0 -3 -1]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [27]:
a = np.random.randint(-10,10,size=(10,10))
print(a)
print(a.min(), a.max())

[[ -2   9  -8   4   8   4   9   8  -3  -7]
 [  6  -6   3   3   4   4   0  -8  -7  -6]
 [ -7  -8  -5   0  -8   6   1  -5   3  -6]
 [  4  -3  -5   4  -8   3  -2   2  -9  -5]
 [  0  -5   7   1  -1  -1  -9   7   5   4]
 [ -7   4  -5  -9   4  -8  -7   1  -8   3]
 [  8   4   1   7   0  -8   8  -9   6  -6]
 [ -8  -9  -8  -6  -3  -6  -8  -6  -9   8]
 [ -4   9   4   3  -5   9   3  -1  -7 -10]
 [-10   4   6 -10  -4   0   7  -5   9   2]]
-10 9


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [32]:
a = np.random.random(30)
print(a)

tot = sum(a)
print (tot/len(a))

[0.46096225 0.75831651 0.89137877 0.65660905 0.60375878 0.07711206
 0.834437   0.98136316 0.90673539 0.09242488 0.7453094  0.49752346
 0.55717543 0.03478236 0.66241019 0.96326504 0.17510041 0.80962897
 0.93187021 0.55570746 0.52697471 0.85170699 0.19111143 0.12736855
 0.57045737 0.39202826 0.46597712 0.2464801  0.65645131 0.16793324]
0.5464119946905351


#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [39]:
a = np.ones((5,5))
print(a)

z = np.zeros((3,3))
a[1:4,1:4] = z
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [40]:
existing_array = np.ones((4,4))
new_array = np.zeros((6,6))
new_array[1:-1,1:-1] = existing_array
print(new_array)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [41]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [45]:
a = np.zeros((5,5))
a[[1,2,3,4],[0,1,2,3]] = [1,2,3,4]
print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [51]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 16. Normalize a 5x5 random matrix (★☆☆)

In [52]:
a = np.random.random((5,5))
amax, amin = a.max(), a.min()
a = (a-amin)/(amax-amin)
print (a)

[[0.44069277 0.36283905 0.86054226 0.83778243 0.77808979]
 [0.30962625 0.89074624 0.91986035 0.17633158 0.05620672]
 [0.75593487 0.42186951 0.87468818 0.11796216 0.1501004 ]
 [0.3250938  0.75198695 0.33352456 0.40241637 0.91479402]
 [1.         0.76607739 0.77255529 0.73773008 0.        ]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [55]:
a =  np.arange(20)

a[3<a and a <8] *= -1

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 18. How to round away from zero a float array ? (★☆☆)

In [57]:
array = np.array([1.,2.,3.,4.,5.])
res = np.round(array)
res

array([1., 2., 3., 4., 5.])

#### 19. Find common values between two arrays? (★☆☆)

In [58]:
a1= np.array([1,2,3,4,5,6])
a2= np.array([3,4,5,6,7,8])

print(np.intersect1d(a1,a2))

[3 4 5 6]


#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [59]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-59-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [260]:
a = np.random.randint((5,5,5))
print(a)

[1 4 1]


#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [261]:
a = np.linspace(0,1,12,endpoint=True)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 23. Create a random vector of size 10 and sort it (★★☆)

In [288]:
a = np.random.random(10)

a.sort()
print(a)


[0.07791187 0.2326657  0.37211467 0.42297894 0.59870991 0.75006588
 0.77220971 0.84251481 0.88906796 0.97113392]


#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [290]:
a = np.array((1,2,3,4,5))
b = np.array((1,2,3,4,5))

print(np.allclose(a,b))

True


#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [301]:
a = np.random.random(10)
a[a.argmax()]=0
print(a)

[0.53539499 0.3263125  0.0374931  0.10601558 0.63987831 0.91466084
 0.0800152  0.67449202 0.73076159 0.        ]


#### 26. Find the closest value to random element in a vector? (★★☆)

In [306]:
a = np.array([2, 42, 82, 122, 162, 202, 242, 282, 322, 362])
number = 112


def closest (num, arr):
    curr = arr[0]
    for x in arr:
        if abs (num - x) < abs (num - curr):
            curr = x
    return curr

print (closest(number, a))

122


#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [308]:
a = np.array((1.,2.,3.,5.,6.,))
b = a.astype(int)
print (b)

[1 2 3 5 6]


#### 28. Sort an array by the nth column? (★★☆)

#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 31. Swap two rows of an array? (★★★)

#### 32. How to negate a boolean value inside an array? (★★★)

#### 33. Find the most frequent value in an array?

#### 34. Get the n largest values of an array (★★★)

#### 35. Extract unique rows from a two dimensional array? (★★★)